boat/urls.py
from django.urls import path
from .apps import BoatConfig
from . import views

app_name = BoatConfig.name

urlpatterns = [
    path("", views.BoatListView.as_view(), name="boat_list"),
    path("<int:pk>/", views.BoatDetailView.as_view(), name="boat_detail"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("boat.urls", namespace="boat")),
    path("order/", include("order.urls", namespace="order")),
]

order/urls.py
from django.urls import path

from .apps import OrderConfig

app_name = OrderConfig.name
from . import views

urlpatterns = [
    path("create/<int:pk>/", views.OrderCreateView.as_view(), name="order_create"),
]

boat/models.py
from django.db import models

NULLABLE = {"blank": True, "null": True}


class Owner(models.Model):
    name = models.CharField(max_length=255, verbose_name="Имя")
    email = models.EmailField(verbose_name="Почта", unique=True)

    def __str__(self):
        return f"{self.email} ({self.name})"

    class Meta:
        verbose_name = "Владелец"
        verbose_name_plural = "Владельцы"


class Boat(models.Model):
    name = models.CharField(max_length=50, verbose_name="Название")
    year = models.PositiveSmallIntegerField(**NULLABLE, verbose_name="год выпуска")
    owner = models.ForeignKey(Owner, on_delete=models.CASCADE, verbose_name="Владелец")
    price = models.IntegerField(**NULLABLE, verbose_name="Цена")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Лодка"
        verbose_name_plural = "Лодки"


class BoatHistory(models.Model):
    boat = models.ForeignKey(Boat, on_delete=models.CASCADE, verbose_name="Лодка")
    owner = models.ForeignKey(
        Owner, on_delete=models.SET_NULL, verbose_name="Владелец", **NULLABLE
    )

    start_year = models.PositiveSmallIntegerField(**NULLABLE, verbose_name="Владение с")
    stop_year = models.PositiveSmallIntegerField(**NULLABLE, verbose_name="Владение по")

    def __str__(self):
        return f"{self.boat} {self.start_year}-{self.stop_year}"

    class Meta:
        verbose_name = "История"
        verbose_name_plural = "Истории"

order/models.py
from django.db import models


class Order(models.Model):
    boat = models.ForeignKey(
        "boat.Boat", on_delete=models.CASCADE, verbose_name="лодка"
    )
    name = models.CharField(max_length=150, verbose_name="Имя")
    email = models.EmailField(max_length=150, verbose_name="Почта")
    message = models.TextField(verbose_name="Сообщение")
    closed = models.BooleanField(default=False, verbose_name="Сделка завершена")

    created_at = models.DateTimeField(
        auto_now_add=True, verbose_name="Дата и время создания"
    )

    def __str__(self):
        return f"{self.boat} от {self.email}"

    class Meta:
        verbose_name = "Заявка"
        verbose_name_plural = "Заявки"

boat/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Boat


class BoatListView(ListView):
    model = Boat


class BoatDetailView(DetailView):
    model = Boat

order/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import CreateView
from .models import Order
from boat.models import Boat
from django.urls import reverse

from .services import send_order_email


class OrderCreateView(CreateView):
    model = Order
    fields = ["boat", "name", "email", "message"]

    def get_success_url(self):
        return reverse("boat:boat_detail", args=[self.kwargs.get("pk")])

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data["boat"] = get_object_or_404(Boat, pk=self.kwargs.get("pk"))
        return context_data

    def form_valid(self, form):
        obj = form.save()
        send_order_email(obj)
        return super().form_valid(form)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" data-bs-theme="auto">
    <head>
        <title>
            {% block title %}
            {% endblock title %}
        </title>
        {% include 'includes/head.html' %}
    </head>


    <body>
        {% include 'includes/top.html' %}
        <div class="container py-3">

            {% include 'includes/header.html' %}
            <main>

                {% block content %}
                {% endblock content %}

                {% comment %}
                {% include 'includes/compare_plans.html' %}

                {% endcomment %}
            </main>
            {% include 'includes/footer.html' %}
        </div>






        <script src="{% static 'js/bootstrap.bundle.min.js' %}" ></script>
    </body>
</html>

templates/boat/boat_detail.html
{% extends 'base.html' %}

{% block title %}
{{ object.name }}
{% endblock %}

{% block content %}

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">{{ object.name }}</div>
            <div class="card-body">
                <table class="table table-stripped">
                    <tr>
                        <th>Начало</th>
                        <th>Окончание</th>
                        <th>Владелец</th>
                    </tr>

                    {% for history_item in object.boathistory_set.all %}
                    <tr>
                        <td>{{ history_item.start_year }}</td>
                        <td>{{ history_item.stop_year }}</td>
                        <td>
                            {% if history_item.owner %}
                            {{ history_item.owner }}
                            {% else %}
                            не указан
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}

                </table>
            </div>
            <div class="card-footer">
                <a href="{% url 'order:order_create' object.pk %}" class="btn btn-outline-success">Оставить заявку</a>
            </div>
        </div>
    </div>
</div>


{% endblock %}

templates/boat/boat_list.html
{% extends 'base.html' %}

{% block title %}
Продажа лодок
{% endblock title %}

{% block content %}

<div class="row row-cols-1 row-cols-md-3 mb-3 text-center">

    {% for object in object_list %}
    <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm">
            <div class="card-header py-3"><h4 class="my-0 fw-normal">{{ object.name }}</h4></div>

            <div class="card-body">
                {% if object.price %}

                <h3 class="card-title pricing-card-title">{{ object.price }}
                    <small class="text-body-secondary fw-light">руб.</small>
                </h3>

                {% else %}

                <h3 class="card-title pricing-card-title">
                    <small class="text-body-secondary fw-light">Цена не указана</small>

                    </h3>


                {% endif %}



                <a href="{% url 'boat:boat_detail' object.pk %}" type="button" class="w-100 btn btn-lg btn-outline-primary">
                    Информация
                </a>
            </div>
        </div>
    </div>
    {% endfor %}

</div>

{% endblock content %}

templates/includes/compare_plans.html
                <h2 class="display-6 text-center mb-4"></h2>
                <div class="table-responsive">
                    <table class="table text-center">
                        <thead>
                            <tr>
                                <th style="width: 34%;"></th>
                                <th style="width: 22%;">Free</th>
                                <th style="width: 22%;">Pro</th>
                                <th style="width: 22%;">Enterprise</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <th scope="row" class="text-start">Public</th>
                                <td>
                                    <svg class="bi" width="24" height="24" role="img" aria-label="Included">
                                        <use xlink:href="#check"></use>
                                    </svg>
                                </td>
                                <td>
                                    <svg class="bi" width="24" height="24" role="img" aria-label="Included">
                                        <use xlink:href="#check"></use>
                                    </svg>
                                </td>
                                <td>
                                    <svg class="bi" width="24" height="24" role="img" aria-label="Included">
                                        <use xlink:href="#check"></use>
                                    </svg>
                                </td>
                            </tr>
                            <tr>
                                <th scope="row" class="text-start">Private</th>
                                <td></td>
                                <td>
                                    <svg class="bi" width="24" height="24" role="img" aria-label="Included">
                                        <use xlink:href="#check"></use>
                                    </svg>
                                </td>
                                <td>
                                    <svg class="bi" width="24" height="24" role="img" aria-label="Included">
                                        <use xlink:href="#check"></use>
                                    </svg>
                                </td>
                            </tr>
                        </tbody>
                        <tbody>
                            <tr>
                                <th scope="row" class="text-start">Permissions</th>
                                <td>
                                    <svg class="bi" width="24" height="24" role="img" aria-label="Included">
                                        <use xlink:href="#check"></use>
                                    </svg>
                                </td>
                                <td>
                                    <svg class="bi" width="24" height="24" role="img" aria-label="Included">
                                        <use xlink:href="#check"></use>
                                    </svg>
                                </td>
                                <td>
                                    <svg class="bi" width="24" height="24" role="img" aria-label="Included">
                                        <use xlink:href="#check"></use>
                                    </svg>
                                </td>
                            </tr>
                            <tr>
                                <th scope="row" class="text-start">Sharing</th>
                                <td></td>
                                <td>
                                    <svg class="bi" width="24" height="24" role="img" aria-label="Included">
                                        <use xlink:href="#check"></use>
                                    </svg>
                                </td>
                                <td>
                                    <svg class="bi" width="24" height="24" role="img" aria-label="Included">
                                        <use xlink:href="#check"></use>
                                    </svg>
                                </td>
                            </tr>
                            <tr>
                                <th scope="row" class="text-start">Unlimited members</th>
                                <td></td>
                                <td>
                                    <svg class="bi" width="24" height="24" role="img" aria-label="Included">
                                        <use xlink:href="#check"></use>
                                    </svg>
                                </td>
                                <td>
                                    <svg class="bi" width="24" height="24" role="img" aria-label="Included">
                                        <use xlink:href="#check"></use>
                                    </svg>
                                </td>
                            </tr>
                            <tr>
                                <th scope="row" class="text-start">Extra security</th>
                                <td></td>
                                <td></td>
                                <td>
                                    <svg class="bi" width="24" height="24" role="img" aria-label="Included">
                                        <use xlink:href="#check"></use>
                                    </svg>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>

templates/includes/footer.html
{% load static %}


<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
        <div class="col-12 col-md"><img class="mb-2" src="{% static 'bootstrap-logo.svg' %}" alt=""
                                        width="24" height="19"> <small class="d-block mb-3 text-body-secondary">&copy;
            2017–2025</small></div>
        <div class="col-6 col-md"><h5>Features</h5>
            <ul class="list-unstyled text-small">
                <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Cool stuff</a></li>
                <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Random feature</a></li>
                <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Team feature</a></li>
                <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Stuff for developers</a>
                </li>
                <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Another one</a></li>
                <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Last time</a></li>
            </ul>
        </div>
        <div class="col-6 col-md"><h5>Resources</h5>
            <ul class="list-unstyled text-small">
                <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Resource</a></li>
                <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Resource name</a></li>
                <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Another resource</a></li>
                <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Final resource</a></li>
            </ul>
        </div>
        <div class="col-6 col-md"><h5>About</h5>
            <ul class="list-unstyled text-small">
                <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Team</a></li>
                <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Locations</a></li>
                <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Privacy</a></li>
                <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Terms</a></li>
            </ul>
        </div>
    </div>
</footer>

templates/includes/head.html
{% load static %}


    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="{% static 'color-modes.js' %}"></script>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="apple-touch-icon" href="{% static 'apple-touch-icon.png' %}" sizes="180x180">
    <link rel="icon" href="{% static 'favicon-32x32.png' %}" sizes="32x32" type="image/png">
    <link rel="icon" href="{% static 'favicon-16x16.png' %}" sizes="16x16" type="image/png">
    <link rel="manifest" href="{% static 'manifest.json' %}">
    <link rel="mask-icon" href="{% static 'safari-pinned-tab.svg' %}" color="#712cf9">
    <link rel="icon" href="{% static 'favicon.ico' %}">
    <meta name="theme-color" content="#712cf9">
    <link href="{% static 'pricing.css' %}" rel="stylesheet">







    <style>
    .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select:none
    }

    @media (min-width: 768px) {
        .bd-placeholder-img-lg {
            font-size:3.5rem
        }
    }

    .b-example-divider {
        width: 100%;
        height: 3rem;
        background-color: #0000001a;
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow:inset 0 .5em 1.5em #0000001a, inset 0 .125em .5em #00000026
    }

    .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height:100vh
    }

    .bi {
        vertical-align: -.125em;
        fill:currentColor
    }

    .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y:hidden
    }

    .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling:touch
    }

    .btn-bd-primary {
        --bd-violet-bg: #712cf9;
        --bd-violet-rgb: 112.520718, 44.062154, 249.437846;
        --bs-btn-font-weight: 600;
        --bs-btn-color: var(--bs-white);
        --bs-btn-bg: var(--bd-violet-bg);
        --bs-btn-border-color: var(--bd-violet-bg);
        --bs-btn-hover-color: var(--bs-white);
        --bs-btn-hover-bg: #6528e0;
        --bs-btn-hover-border-color: #6528e0;
        --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
        --bs-btn-active-color: var(--bs-btn-hover-color);
        --bs-btn-active-bg: #5a23c8;
        --bs-btn-active-border-color: #5a23c8
    }

    .bd-mode-toggle {
        z-index:1500
    }

    .bd-mode-toggle .bi {
        width: 1em;
        height:1em
    }

    .bd-mode-toggle .dropdown-menu .active .bi {
        display: block !important
    }
    </style>

templates/includes/header.html
<header>
    <div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom"><a href="/"
                                                                                              class="d-flex align-items-center link-body-emphasis text-decoration-none">
        <svg xmlns="http://www.w3.org/2000/svg" width="40" height="32" class="me-2" viewBox="0 0 118 94" role="img">
            <title>Продажа лодок</title>
            <path fill-rule="evenodd" clip-rule="evenodd"
                  d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z"
                  fill="currentColor"></path>
        </svg>
        <span class="fs-4">Продажа лодок</span> </a>
        <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto"><a
            class="me-3 py-2 link-body-emphasis text-decoration-none" href="{% url 'boat:boat_list' %}">Лодки</a> <a
                class="me-3 py-2 link-body-emphasis text-decoration-none" href="#">Enterprise</a> <a
                    class="me-3 py-2 link-body-emphasis text-decoration-none" href="#">Support</a> <a
                        class="py-2 link-body-emphasis text-decoration-none" href="#">Pricing</a></nav>
    </div>
    <div class="pricing-header p-3 pb-md-4 mx-auto text-center"><h1 class="display-4 fw-normal text-body-emphasis">
        Продажа лодок</h1>
        </div>
</header>

templates/includes/top.html
<svg xmlns="http://www.w3.org/2000/svg" class="d-none">
    <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"></path>
    </symbol>
    <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"></path>
    </symbol>
    <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"></path>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"></path>
    </symbol>
    <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"></path>
    </symbol>
</svg>


<div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
    <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center" id="bd-theme" type="button"
            aria-expanded="false" data-bs-toggle="dropdown" aria-label="Toggle theme (auto)">
        <svg class="bi my-1 theme-icon-active" aria-hidden="true">
            <use href="#circle-half"></use>
        </svg>
        <span class="visually-hidden" id="bd-theme-text">Toggle theme</span></button>
    <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light"
                    aria-pressed="false">
                <svg class="bi me-2 opacity-50" aria-hidden="true">
                    <use href="#sun-fill"></use>
                </svg>
                Light
                <svg class="bi ms-auto d-none" aria-hidden="true">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark"
                    aria-pressed="false">
                <svg class="bi me-2 opacity-50" aria-hidden="true">
                    <use href="#moon-stars-fill"></use>
                </svg>
                Dark
                <svg class="bi ms-auto d-none" aria-hidden="true">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto"
                    aria-pressed="true">
                <svg class="bi me-2 opacity-50" aria-hidden="true">
                    <use href="#circle-half"></use>
                </svg>
                Auto
                <svg class="bi ms-auto d-none" aria-hidden="true">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
    </ul>
</div>


<svg xmlns="http://www.w3.org/2000/svg" class="d-none">
    <symbol id="check" viewBox="0 0 16 16"><title>Check</title>
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"></path>
    </symbol>
</svg>

templates/order/order_form.html
{% extends 'base.html' %}

{% block title %}
Оформление заявки
{% endblock title %}

{% block content %}

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">Оформление заявки на лодку {{ boat }}</div>
            <div class="card-body">

                <form method="post">
                    {% csrf_token %}
                    <input type="hidden" name="boat" value="{{ boat.pk }}">
                    {{ form.as_p }}
                    <button class="btn btn-outline-success">
                        Оставить заявку
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>


{% endblock %}